### ISSUE TITLE
Status update?

### ISSUE THREAD

**Issue by svm96** [sixeyed/docker-succinctly#1]
Not exactly an issue, but since nothing's been updated in this repo for 10 months I really wanted to know the current status of the book.

**Comment by sixeyed** [comment]
Good question. The copy for the book was finished a while ago. I checked with Syncfusion, and they have a a lot in the publishing queue. This one is scheduled for release in October (!), but hopefully it will come sooner than that. I'll update this repo and post on Twitter `@EltonStoneman` when it does land.
